language: python
python:
    - '3.4'
    - '3.5'
addons:
    postgresql: '9.3'
services:
    - redis-server
install:
    - pip install -r requirements/development.txt
before_script:
    - psql -c 'CREATE DATABASE fastvid;' -U postgres
    - make migrate
script:
    - pep8 .
    - make test
notifications:
    slack: pn101:dSo0orNGFNmtvsEqAhvxPFkf
    email: False
